name: ros_tester
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_vlc_player: ^7.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  web_socket_channel: ^3.0.1
  flutter_joystick: ^0.2.1
  path_provider: ^2.1.5
  google_mobile_ads: ^5.2.0
  fl_chart: ^0.70.2
  shared_preferences: ^2.5.2


flutter:
  uses-material-design: true
  assets:
    - assets/message_types.json
    - assets/mobilio.png


